spring.application.name=backend

spring.datasource.url=jdbc:postgresql://ep-nameless-term-az46iqmm-pooler.c-3.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_PExv7NnH6WDF
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

file.upload.path=upload

file.upload.video=/home/kaju/projects/youtube-clone/upload/videos/
file.upload.thumbnail=/home/kaju/projects/youtube-clone/upload/thumbnails/

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

jwt.secret=VGhpc0lzTXlTdXBlclNlY3JldEtleUZvckpXVDEyMzQ1Njc4OTAxMjM0NTY3ODkw
jwt.expiration=86400000